// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7su2nOPo50ViJgKAOaK0_Wg79-gMsXfk',
    appId: '1:253303220641:web:9d4709e2bbc6799eb683e0',
    messagingSenderId: '253303220641',
    projectId: 'privacypolicy-3033',
    authDomain: 'privacypolicy-3033.firebaseapp.com',
    storageBucket: 'privacypolicy-3033.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmHtLEsqHzGgxgJBnCRIp9ryQaEnnC9Q0',
    appId: '1:253303220641:android:2583eab3fce419e8b683e0',
    messagingSenderId: '253303220641',
    projectId: 'privacypolicy-3033',
    storageBucket: 'privacypolicy-3033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTZMVxcLotaNrRgvBPFHsh_swiUc3WFvA',
    appId: '1:253303220641:ios:39924fcb4834f197b683e0',
    messagingSenderId: '253303220641',
    projectId: 'privacypolicy-3033',
    storageBucket: 'privacypolicy-3033.appspot.com',
    iosBundleId: 'com.example.privacypolicy3303',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTZMVxcLotaNrRgvBPFHsh_swiUc3WFvA',
    appId: '1:253303220641:ios:39924fcb4834f197b683e0',
    messagingSenderId: '253303220641',
    projectId: 'privacypolicy-3033',
    storageBucket: 'privacypolicy-3033.appspot.com',
    iosBundleId: 'com.example.privacypolicy3303',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7su2nOPo50ViJgKAOaK0_Wg79-gMsXfk',
    appId: '1:253303220641:web:68ac640f0669420bb683e0',
    messagingSenderId: '253303220641',
    projectId: 'privacypolicy-3033',
    authDomain: 'privacypolicy-3033.firebaseapp.com',
    storageBucket: 'privacypolicy-3033.appspot.com',
  );
}
